### ISSUE TITLE
Unity同一シーンを複数人で編集する方法

### ISSUE THREAD

**Issue by tissueMO** [manzyun/ggj-2019-made-by-unity-2d#4]
* UnityYamlMergeを使う
* WinMerge的なものでゴリ押しする
* そもそもシーンは別々に作っておき、パッケージ化してマージ先シーンで取り込む

**Comment by manzyun** [comment]
Unityのシーンファイルって、テキストでしたっけ？

多分Gitでちゃんとブランチを切っておけば、
並列作業した後でプルリクエスト受諾によるマージ。
という方法が取れたと思います。

**Comment by tissueMO** [comment]
以前に私以外の方がそのようにマージしていたかもしれません。
一応テキストで保存されるはずなので、その辺のマージツールでも何とかなると思います。
