### ISSUE TITLE
事前実装

### ISSUE THREAD

**Issue by tissueMO** [manzyun/ggj-2019-made-by-unity-2d#5]
やれる範囲でやる。

* 画面フェード（というかトランジション）
    * http://tsubakit1.hateblo.jp/entry/2015/11/04/015355
* カード系（種類数と画面に出す枚数は可変にする）
    * めくる
    * カード移動
    * 並べる
    * 選ぶ
* ローグライク系の処理
    * ランダム生成（手打ちめんどいので自動生成に任せる）
        * 固定配置にしたければ乱数シードを固定値にしてもらう感じで
    * プレイヤー移動（初期位置もランダム）
        * 固定配置にしたければ（ｒｙ
* 複数カメラ
    * 縦割り or 横割り 選択可能に

**Comment by tissueMO** [comment]
結局カード周りしかできなかった上にあんまり使うかどうかも怪しい

**Comment by manzyun** [comment]
大丈夫だ、問題ない。（すごく頼りないかもしれないですが、実装経験値を得れたということで）

**Comment by tissueMO** [comment]
> 実装経験値を得れた

Unity触ったのがそもそも久しぶりだったので、これは大きかったかもしれません。
まあ結局カードの方は使いませんでしたが。。。
