### ISSUE TITLE
解像度を決める

### ISSUE THREAD

**Issue by tissueMO** [manzyun/ggj-2019-made-by-unity-2d#7]
解像度の想定をしておかないと、後々UIで面倒なことになるので一応統一しておく。

**Comment by manzyun** [comment]
もしかして、今どき800x600pxって、小さいですかね……。
自分そのくらいでいいのではないかと思ってしまいました。

**Comment by tissueMO** [comment]
大きさ的にはそのぐらいがちょうどよさそうですね。
しかし、4:3がいいのか、16:9がいいのかは今時のPCゲームを知らないので何とも言えないです…。

**Comment by tissueMO** [comment]
16:9 の 1280x720 でいきます！
